export default {
	common: {
		toolbox: '在线工具箱',
		description: '提供各种实用工具，提高您的工作效率',
		searchResults: '搜索结果',
		allTools: '所有工具',
		tool: '工具',
		copyright: '© {{year}} 工具箱. 保留所有权利。',
		searchPlaceholder: '搜索工具，如：JSON 格式化、时间戳转换...'
	},
	tools: {
		'json-formatter': 'JSON 格式化',
		timestamp: '时间戳转换',
		'uuid-generator': 'UUID/GUID 生成器',
		'base64-codec': 'Base64 编码/解码',
		'url-codec': 'URL 编码/解码',
		'qrcode-generator': '二维码生成器',
		'hash-encoder': '哈希编码工具',
		'html-preview': 'HTML 在线预览',
		'regex-tester': '正则表达式',
		'ip-info': 'IP 信息查看'
	},
	jsonFormatter: {
		indentSize: '缩进量:',
		spaces2: '2 个空格',
		spaces4: '4 个空格',
		validateFormat: '校验并格式化',
		compress: '压缩',
		escape: '转义',
		unescape: '去除转义',
		copy: '复制',
		errorLine: '第 {{line}} 行错误：',
		placeholder: '在此粘贴 JSON 数据...',
		invalidJson: '无效的 JSON 格式',
		validJson: '有效的 JSON 格式',
		enterValidJson: '请先输入有效的 JSON 数据',
		jsonEscaped: 'JSON 已转义',
		jsonUnescaped: '已去除转义',
		processingError: '处理 JSON 时出错',
		copiedToClipboard: '已复制到剪贴板',
		copyFailed: '复制到剪贴板失败'
	},
	timestampConverter: {
		currentTimestamp: '当前时间戳',
		continue: '继续',
		pause: '暂停',
		dateToTimestamp: '日期转时间戳',
		inputDateTime: '输入日期时间',
		convert: '转换',
		conversionResult: '转换结果',
		timestampToDate: '时间戳转日期',
		inputTimestamp: '输入时间戳',
		timestampExample: '例如: 1747977617089',
		dateFormat: '日期格式',
		selectDateFormat: '选择日期格式',
		defaultFormat: '默认格式',
		isoFormat: 'ISO格式',
		localeFormat: '本地格式',
		utcFormat: 'UTC格式',
		copy: '复制',
		timestampCopied: '已复制时间戳',
		dateCopied: '已复制日期',
		invalidDate: '请输入有效的日期',
		invalidTimestamp: '请输入有效的时间戳',
		dateConversionSuccess: '日期转换成功',
		timestampConversionSuccess: '时间戳转换成功'
	},
	uuidGenerator: {
		count: '生成数量',
		useHyphens: '连字符 | -',
		uppercase: '使用大写',
		commaSeparated: '逗号分隔 | ,',
		useQuotes: '引号 | ""',
		generate: '生成 UUID',
		copy: '复制',
		generated: '已生成 {{count}} 个 UUID',
		noUuid: '没有可复制的 UUID',
		copiedToClipboard: '已复制到剪贴板',
		copyFailed: '复制到剪贴板失败',
		placeholder: '点击"生成 UUID"按钮生成 UUID...'
	},
	base64Codec: {
		textEncode: '文本编码',
		fileEncode: '文件编码',
		decode: 'Base64 解码',
		urlSafeMode: "URL 安全模式 (使用 '-' 和 '_' 替代 '+' 和 '/')",
		dataUriFormat: 'Data URI 格式 (输出 data:[mediatype];base64,{data} 格式)',
		inputText: '输入文本',
		inputBase64: '输入 Base64',
		uploadFile: '上传文件进行编码',
		selectFile: '选择文件',
		fileSupport: '支持所有文件类型，最大文件大小: 5MB',
		encode: '编码',
		encodeFile: '编码文件',
		swap: '交换',
		copyResult: '复制结果',
		base64Result: 'Base64 结果',
		fileBase64Result: '文件 Base64 结果',
		decodeResult: '解码结果',
		inputTextPlaceholder: '输入需要编码的文本...',
		inputBase64Placeholder: '输入需要解码的Base64文本...',
		base64ResultPlaceholder: 'Base64 编码结果...',
		fileResultPlaceholder: '文件编码结果...',
		decodeResultPlaceholder: '解码后的文本...',
		encodeSuccess: '编码成功',
		decodeSuccess: '解码成功',
		fileEncodeSuccess: '文件编码成功',
		noInputText: '请先输入需要编码的文本',
		noInputBase64: '请先输入需要解码的Base64文本',
		noFile: '请先选择文件',
		fileSizeExceeded: '文件大小不能超过5MB',
		fileReadError: '读取文件失败',
		encodeError: '编码失败: {{error}}',
		decodeError: '解码失败: {{error}}',
		invalidBase64: '无效的Base64字符串',
		unknownError: '未知错误',
		noCopyContent: '没有可复制的内容',
		copiedToClipboard: '已复制到剪贴板',
		copyFailed: '复制到剪贴板失败',
		fileSelected: '已选择文件: {{name}}'
	},
	urlCodec: {
		encode: 'URL 编码',
		decode: 'URL 解码',
		encodeSpaces: '将空格编码为 %20（不选则编码为 +）',
		encodeAll: '编码所有字符（包括非保留字符）',
		inputText: '输入文本',
		inputUrlText: '输入 URL 编码文本',
		inputTextPlaceholder: '输入需要编码的文本...',
		inputUrlPlaceholder: '输入需要解码的URL编码文本...',
		urlEncodeResult: 'URL 编码结果',
		urlDecodeResult: 'URL 解码结果',
		urlEncodePlaceholder: 'URL 编码结果...',
		urlDecodePlaceholder: '解码后的文本...',
		encodeSuccess: '编码成功',
		decodeSuccess: '解码成功',
		noInputText: '请先输入需要编码的文本',
		noInputUrl: '请先输入需要解码的URL文本',
		encodeError: '编码失败: {{error}}',
		decodeError: '解码失败: {{error}}',
		invalidUrlEncoding: '无效的URL编码字符串',
		unknownError: '未知错误',
		noCopyContent: '没有可复制的内容',
		copiedToClipboard: '已复制到剪贴板',
		copyFailed: '复制到剪贴板失败',
		swap: '交换'
	},
	qrcodeGenerator: {
		content: '二维码内容',
		contentPlaceholder: '输入要生成二维码的文本、URL或其他内容...',
		errorCorrectionLevel: '容错级别',
		selectErrorLevel: '选择容错级别',
		errorLevelL: '低 (L - 7%)',
		errorLevelM: '中 (M - 15%)',
		errorLevelQ: '高 (Q - 25%)',
		errorLevelH: '最高 (H - 30%)',
		size: '尺寸: {{size}}x{{size}} 像素',
		qrColor: '二维码颜色',
		backgroundColor: '背景颜色',
		generate: '生成二维码',
		download: '下载',
		generateSuccess: '二维码已生成',
		generateError: '生成二维码时出错',
		noQrToDownload: '没有可下载的二维码',
		downloadSuccess: '二维码已下载',
		enterContent: '输入内容生成二维码'
	},
	hashEncoder: {
		textHash: '文本哈希',
		fileHash: '文件哈希',
		selectAlgorithm: '选择哈希算法',
		hmacKey: 'HMAC 密钥',
		hmacKeyPlaceholder: '输入HMAC密钥...',
		inputText: '输入文本',
		inputTextPlaceholder: '输入需要哈希的文本...',
		uploadFile: '上传文件进行哈希',
		selectFile: '选择文件',
		fileSupport: '支持所有文件类型，最大文件大小: 10MB',
		calculate: '计算哈希',
		calculateFileHash: '计算文件哈希',
		copyResult: '复制结果',
		hashResult: '哈希结果',
		hashResultPlaceholder: '哈希计算结果...',
		noInputText: '请先输入需要哈希的文本',
		hmacKeyRequired: '使用HMAC算法时必须提供密钥',
		hashSuccess: '哈希计算成功',
		fileHashSuccess: '文件哈希计算成功',
		hashError: '哈希计算失败: {{error}}',
		noFile: '请先选择文件',
		fileSizeExceeded: '文件大小不能超过10MB',
		noCopyContent: '没有可复制的内容',
		copiedToClipboard: '已复制到剪贴板',
		copyFailed: '复制到剪贴板失败',
		fileSelected: '已选择文件: {{name}}'
	},
	htmlPreview: {
		title: 'HTML 在线预览工具',
		formatCode: '格式化代码',
		copyCode: '复制代码',
		refreshPreview: '刷新预览',
		codePlaceholder: '在此输入HTML代码...',
		noHtmlCode: '请先输入HTML代码',
		formatSuccess: '代码格式化成功',
		formatError: '格式化失败: {{error}}',
		copiedToClipboard: '已复制到剪贴板',
		copyFailed: '复制到剪贴板失败',
		previewRefreshed: '预览已刷新',
		sampleTitle: 'HTML 在线预览示例',
		sampleDescription:
			'这是一个简单的 HTML 预览示例。您可以在左侧编辑器中修改代码，右侧会实时显示预览效果。',
		sampleSupport:
			'支持 <span class="highlight">HTML</span> 和 <span class="highlight">CSS</span> 代码。'
	},
	regexTester: {
		title: '正则表达式测试工具',
		regexPattern: '正则表达式',
		flags: '标志',
		testText: '测试文本',
		commonPatterns: '常用正则表达式',
		syntaxReference: '语法参考',
		characterClasses: '字符类',
		quantifiers: '量词',
		anchors: '锚点',
		groups: '分组和引用',
		specialChars: '特殊字符',
		flagsReference: '标志',
		patternPlaceholder: '输入正则表达式，例如: \\b\\w+\\b',
		flagsPlaceholder: '标志',
		testTextPlaceholder: '在此输入要测试的文本...',
		matchesFound: '找到 {{count}} 个匹配项',
		regexError: '正则表达式错误: {{message}}',
		// Common patterns
		emailPattern: '邮箱地址',
		phonePattern: '中国大陆手机号码',
		urlPattern: 'URL',
		idCardPattern: '中国大陆身份证号',
		ipv4Pattern: 'IPv4地址',
		ipv6Pattern: 'IPv6地址',
		datePattern: '日期',
		chinesePattern: '中文字符',
		// Syntax reference descriptions
		dotDesc: '匹配除换行符外的任何单个字符',
		digitDesc: '匹配任何数字字符 (0-9)',
		nonDigitDesc: '匹配任何非数字字符',
		wordDesc: '匹配任何字母数字字符 (a-z, A-Z, 0-9, _)',
		nonWordDesc: '匹配任何非字母数字字符',
		whitespaceDesc: '匹配任何空白字符 (空格, 制表符, 换行符等)',
		nonWhitespaceDesc: '匹配任何非空白字符',
		starDesc: '匹配前面的表达式 0 次或多次',
		plusDesc: '匹配前面的表达式 1 次或多次',
		questionDesc: '匹配前面的表达式 0 次或 1 次',
		exactDesc: '匹配前面的表达式恰好 n 次',
		minDesc: '匹配前面的表达式至少 n 次',
		rangeDesc: '匹配前面的表达式至少 n 次，最多 m 次',
		startDesc: '匹配字符串的开头',
		endDesc: '匹配字符串的结尾',
		wordBoundaryDesc: '匹配单词边界',
		nonWordBoundaryDesc: '匹配非单词边界',
		globalDesc: '全局匹配 (查找所有匹配项)',
		ignoreCaseDesc: '忽略大小写',
		multilineDesc: '多行匹配',
		dotAllDesc: '允许 . 匹配换行符',
		unicodeDesc: 'Unicode 模式',
		stickyDesc: '粘性匹配',
		captureGroupDesc: '捕获组，匹配括号内的表达式',
		nonCaptureGroupDesc: '非捕获组',
		backreferenceDesc: '反向引用，引用之前的捕获组',
		orDesc: '或运算符，匹配 | 前或后的表达式',
		charSetDesc: '字符集，匹配括号内的任意一个字符',
		negatedCharSetDesc: '否定字符集，匹配不在括号内的任意一个字符',
		charRangeDesc: '字符范围，匹配指定范围内的任意一个字符',
		escapeDesc: '转义字符，用于匹配特殊字符本身'
	},
	ipInfo: {
		title: 'IP 信息查看工具',
		description: '查看 IP 地址的详细信息，包括 ASN、地理位置、公司信息等。',
		inputIp: '输入 IP 地址',
		ipPlaceholder: '例如: 8.8.8.8',
		search: '查询',
		searching: '查询中...',
		searchMyIp: '查询本机IP',
		// Information sections
		basicInfo: '基本信息',
		locationInfo: '位置信息',
		privacyNetworkInfo: '隐私和网络信息',
		// Basic information fields
		ipAddress: 'IP 地址',
		asn: 'ASN',
		ipRange: 'IP 范围',
		company: '公司',
		asnType: 'ASN 类型',
		abuseContact: '滥用联系方式',
		// Location information fields
		city: '城市',
		state: '州/省',
		country: '国家',
		coordinates: '坐标',
		localTime: '本地时间',
		timezone: '时区',
		// Privacy information fields
		privateIp: '私密IP',
		anycast: 'Anycast',
		privateIpDesc: '此 IP 是否使用 VPN 或其他方法隐藏',
		anycastDesc: '任播(Anycast)地址是多个系统共享的地址',
		yes: '是',
		no: '否'
	}
};
